version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'app-bd'
    ports:
    - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_DB=postgres'

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'spring-app'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=admin'